
<pre>
<center><b><h1>Machine Learning</b></center>

<center><b><h1>Lab - 3</b></center>
<pre>  

# 📱 Lab: Scikit-Learn Fundamentals (Google Play Store)

**Objective:** Transition from manual data cleaning to automated Machine Learning preprocessing using Scikit-Learn.

**Prerequisites:**
* Ensure you have the `googleplaystore_cleaned.csv` file (from the previous lab) in this folder.

### 1. Load Preprocessed Data
**Instruction:** Load the dataset you cleaned in the previous lab. This dataset should already have `Installs`, `Price`, and `Reviews` converted to numbers.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import sklearn

### Intro to Scikit-Learn
**What is Scikit-Learn?**
It is the standard library for Machine Learning in Python. We use it for:
1.  **Preprocessing:** Scaling numbers and encoding text.
2.  **Modeling:** Training algorithms.
3.  **Evaluation:** Checking accuracy.

**Task:** Import `sklearn` and check the version.

In [5]:
df = pd.read_csv("/content/google_data.csv")

In [9]:
df

Unnamed: 0                                                App  \
0              0     Photo Editor & Candy Camera & Grid & ScrapBook   
1              1                                Coloring book moana   
2              2  U Launcher Lite – FREE Live Cool Themes, Hide ...   
3              3                              Sketch - Draw & Paint   
4              4              Pixel Draw - Number Art Coloring Book   
...          ...                                                ...   
8816       10835                                           FR Forms   
8817       10836                                   Sya9a Maroc - FR   
8818       10837                   Fr. Mike Schmitz Audio Teachings   
8819       10838                             Parkinson Exercices FR   
8820       10840      iHoroscope - 2018 Daily Horoscope & Astrology   

            Category  Rating  Reviews        Size    Installs  Type  Price  \
0     ART_AND_DESIGN     4.1      159  19000000.0     10000.0  Free    0.0   
1     ART_AND_DESIGN     3.9      967  14000000.0    500000.0  Free    0.0   
2     ART_AND_DESIGN     4.7    87510   8700000.0   5000000.0  Free    0.0   
3     ART_AND_DESIGN     4.5   215644  25000000.0  50000000.0  Free    0.0   
4     ART_AND_DESIGN     4.3      967   2800000.0    100000.0  Free    0.0   
...              ...     ...      ...         ...         ...   ...    ...   
8816        BUSINESS     4.3        0   9600000.0        10.0  Free    0.0   
8817          FAMILY     4.5       38  53000000.0      5000.0  Free    0.0   
8818          FAMILY     5.0        4   3600000.0       100.0  Free    0.0   
8819         MEDICAL     4.3        3   9500000.0      1000.0  Free    0.0   
8820       LIFESTYLE     4.5   398307  19000000.0  10000000.0  Free    0.0   

     Content Rating                     Genres        Last Updated  \
0          Everyone               Art & Design     January 7, 2018   
1          Everyone  Art & Design;Pretend Play    January 15, 2018   
2          Everyone               Art & Design      August 1, 2018   
3              Teen               Art & Design        June 8, 2018   
4          Everyone    Art & Design;Creativity       June 20, 2018   
...             ...                        ...                 ...   
8816       Everyone                   Business  September 29, 2016   
8817       Everyone                  Education       July 25, 2017   
8818       Everyone                  Education        July 6, 2018   
8819       Everyone                    Medical    January 20, 2017   
8820       Everyone                  Lifestyle       July 25, 2018   

             Current Ver         Android Ver  
0                  1.0.0        4.0.3 and up  
1                  2.0.0        4.0.3 and up  
2                  1.2.4        4.0.3 and up  
3     Varies with device          4.2 and up  
4                    1.1          4.4 and up  
...                  ...                 ...  
8816               1.1.5          4.0 and up  
8817                1.48          4.1 and up  
8818                 1.0          4.1 and up  
8819                 1.0          2.2 and up  
8820  Varies with device  Varies with device  

[8821 rows x 14 columns]

In [6]:
##__version__
print("Scikit-learn version: {sklearn.__version__}")

Scikit-learn version: {sklearn.__version__}


### 3.  Train_Test_Split
**Concept:** We split data to prevent "Overfitting". The model learns from the **Train** set and is tested on the **Test** set.

**Task:**
1. Define `X` (Features: everything except Rating/App) and `y` (Target: Rating).
2. Split the data (80% Train, 20% Test).

In [12]:
# train_test_split

from sklearn.model_selection import train_test_split

X = df.drop(['Rating','App'],axis=1)
y= df["Rating"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("Training Shape: ",X_train.shape)
print("Testing Shape: ",X_test.shape)


Training Shape:  (7056, 12)
Testing Shape:  (1765, 12)


### 4. 📏 Scaling Numerical Data (StandardScaler)
**Concept:** `Installs` (Millions) are much larger than `Rating` (1-5). We scale them so the model treats them equally.

**Task:** Use `StandardScaler` on the numerical columns.

In [14]:
#data long hoi to standardize na rye atle a ne proper equal karva pade

#StandardScaler()
#fit_transform()

from sklearn.preprocessing import StandardScaler
num_cols=['Reviews','Size','Installs','Price']

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train[num_cols])

print("Scaled Data sample: ",X_train_scaled)

Scaled Data sample:  [[-0.04165443 -0.65937412  0.07693281 -0.06729974]
 [-0.14321967 -0.82894166 -0.15725882 -0.06729974]
 [-0.14237874 -0.49873119 -0.1549285  -0.06729974]
 ...
 [-0.14318712  0.17061436 -0.15724711 -0.06729974]
 [-0.03250245  1.59855152 -0.04016886 -0.06729974]
 [-0.1007897   0.30448346 -0.1338502  -0.06729974]]


### 5. 🔠 Encoding Categorical Data
**Concept:** Models need numbers, not text like "Business" or "Teen".

**Method A: Pandas `get_dummies` (Simple)**

In [15]:
#get_dummies
# pd.get_dummies -> unique data find kari aape j numerical na hoi a

dummies = pd.get_dummies(X_train['Content Rating'])

dummies.head()

Adults only 18+  Everyone  Everyone 10+  Mature 17+   Teen  Unrated
3254            False      True         False       False  False    False
4353            False      True         False       False  False    False
786             False     False          True       False  False    False
6149            False     False         False       False   True    False
449             False     False         False       False   True    False

**Method B: Sklearn `OneHotEncoder` (Professional)**

In [16]:
#OneHotEncoder
#fit_transform

# aa sklearn vadu che j categorical data ne numerical identify karine aape

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore')

cat_encoded = encoder.fit_transform(X_train[['Category']])

print("Encoded Shape: ", cat_encoded.shape)

Encoded Shape:  (7056, 33)


### 6. 🚀 The Full Pipeline: ColumnTransformer
**Concept:** Instead of doing steps 4 and 5 manually, we wrap them in one object.

**Task:** Create a `ColumnTransformer` that Scales numerical data AND Encodes categorical data at the same time.

In [17]:
from sklearn.compose import ColumnTransformer

In [18]:
numeric_features = ['Reviews', 'Size', 'Installs', 'Price']
categorical_features = ['Category', 'Content Rating']

In [37]:
# Create ColumnTransformer

# aayathi naam new vada generate thay che
preprocessor = ColumnTransformer(
    transformers=[
        # ('name',Transformer(), columns)
        ('num',StandardScaler(),numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'),categorical_features)
    ]
)

In [38]:
from sklearn.pipeline import Pipeline

In [39]:
# csv or df ma changes nathi thata, categorical change numerical ma thay a navij column bane che

pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

In [40]:
X_processed = pipeline.fit_transform(X)

In [41]:
pipeline
# 1.5 version

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Reviews', 'Size',
                                                   'Installs', 'Price']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Category',
                                                   'Content Rating'])]))])

In [42]:
X = X_train[numeric_features + categorical_features]

In [43]:
print(f"Original Shape: {X.shape}")
print(f"Processed Shape: {X_processed.shape}")

Original Shape: (7056, 6)
Processed Shape: (7056, 43)


In [44]:
new_columns = pipeline.named_steps['preprocessor'].get_features_names_out()

df_processed = pd.Dataframe(X_processed.toarray(), columns=new_cloumns)

df_processed.head()

AttributeError: 'ColumnTransformer' object has no attribute 'get_features_names_out'